### PR TITLE
Add ML Models and Pandas Profile

### PR DESCRIPTION
**Pull request by hemanth-kotagiri**
Hi, @RajavarunXD 
### Brief overview of the changes
- Used Pandas Profiling to generate a web-page which has done the EDA cohesively on the entire dataset covering everything from available variables, interactions and, correlation between columns.
- Using the Scikit-Learn library, implemented **text classification using _multiple ML algorithms_**. Currently, implemented these three models
1. **Logistic Regression (75 % accuracy)**
2. **Naive Bayes Classification (73% accuracy)**
3. **Bernoulli Naive Bayes Classification (80 % accuracy)**
- At the end, I have generated the **confusion matrix** for all the three models.

### CODE REVIEW

**Comment by sairohith-xdinv** [comment]
@RajavarunXD, could you review the code & leave your comments/approve ASAP?

**Comment by hemanth-kotagiri** [comment]
@sairohith-xdinv @RajavarunXD It has been over 20 days. Please do drop in the material/topics also to be revised by me for the phase 2 that we have planned.

**Review by RajavarunXD — APPROVED** [review]

**Comment by RajavarunXD** [comment]
Sorry for the late reply @hemanth-kotagiri  
I was stuck between three projects and could not make time. At present we are busy wrapping phase 1. Let us connect when we three are free.

**Comment by hemanth-kotagiri** [comment]
Thank you for the response @RajavarunXD . It's okay and I understand that you're quite busy.

**Comment by hemanth-kotagiri** [comment]
@sairohith-xdinv Is there anything more to be done to merge the code? If there is anything missing from my end, please let me know.

**Comment by hemanth-kotagiri** [comment]
Is there anything that needs to be done to merge the code, @sairohith-xdinv ? If there's anything to be done from my end, please lemme know.

**Comment by sairohith-xdinv** [comment]
@hemanth-kotagiri, there is nothing to be done from your end. Seems like the automatic merge has not been configured at the time this PR was started. Merging & closing it now.

**Pull request merged**
